FROM node:22.12.0-alpine AS base

ARG NEXT_PUBLIC_NODE_ENV=production
ENV NEXT_PUBLIC_NODE_ENV=${NEXT_PUBLIC_NODE_ENV}

# ---------- deps ----------
FROM base AS deps

WORKDIR /app

COPY package*.json ./

RUN npm ci

# # ---------- build ----------
# FROM base AS builder
# WORKDIR /app
# COPY --from=deps /app/node_modules ./node_modules
# COPY . .

# RUN npm run build

# # ---------- run ----------
# FROM base AS runner
# WORKDIR /app

# ENV NODE_ENV production

# RUN addgroup --system --gid 1001 nodejs
# RUN adduser --system --uid 1001 nextjs

# COPY --from=builder /app/public ./public

# RUN mkdir .next
# RUN chown nextjs:nodejs .next

# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# USER nextjs

# EXPOSE 3002

# ENV PORT 3002

# CMD HOSTNAME="0.0.0.0" node server.js
